# Generated by Django 5.2.4 on 2025-07-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askgptapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('needs_followup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Query',
                'verbose_name_plural': 'User Queries',
            },
        ),
    ]
